<div class="alert alert-block alert-info" style="margin-top: 20px">
    <a href="https://cocl.us/PY0101EN_edx_add_top">
         <img src="https://s3-api.us-geo.objectstorage.softlayer.net/cf-courses-data/CognitiveClass/PY0101EN/Ad/TopAd.png" width="750" align="center">
    </a>
</div>

<a href="https://cognitiveclass.ai/">
    <img src="https://s3-api.us-geo.objectstorage.softlayer.net/cf-courses-data/CognitiveClass/PY0101EN/Ad/CCLog.png" width="200" align="center">
</a>

<h1>Arreglos de Dos Dimensiones <code>Numpy</code> en Python</h1>

<p><strong>¡Bienvenido!</strong> En este cuaderno aprenderás acerca de <code>Numpy</code> en el Lenguaje de Programación Python. Al final de este laboratorio, sabrás lo que es <code>Numpy</code> y sus operaciones.</p>

<h2>Tabla de Contenido</h2>
<div class="alert alert-block alert-info" style="margin-top: 20px">
    <ul>
        <li><a href="create">Crear un Arreglo de Dos Dimensiones Numpy</a></li>
        <li><a href="access">Acceder a los Elemento de un Arreglo Numpy</a></li>
        <li><a href="op">Operaciones Básicas</a></li>
    </ul>
    <p>
        Tiempo Estimado: <strong>20 min</strong>
    </p>
</div>

<hr>

<h2 id="create">Crear un Arreglo de Dos Dimensiones Numpy</h2>

In [1]:
# Importar librerias

import numpy as np 
import matplotlib.pyplot as plt

Considera la lista <code>a</code>, esta lista contiene tres listas anidadas **del mismo tamaño**.

In [2]:
# Crear una lista

a = [[11, 12, 13], [21, 22, 23], [31, 32, 33]]
a

[[11, 12, 13], [21, 22, 23], [31, 32, 33]]

Podemos convertir la lista en un Arreglo Numpy de la siguiente forma:

In [3]:
# Convertir la lista en un Arreglo Numpy
# Cada elemento es del mismo tipo

A = np.array(a)
A

array([[11, 12, 13],
       [21, 22, 23],
       [31, 32, 33]])

Podemos usar el atributo <code>ndim</code> para obtener el numero de dimensiones.

In [4]:
# Muestra las dimensiones del arreglo

A.ndim

2

El atributo <code>shape</code> regresa una tupla que corresponde al tamaño o numero de cada dimensión.

In [5]:
# Muestra la forma del arreglo

A.shape

(3, 3)

El número total de elementos en el arreglo esta dado por el atributo <code>size</code>.

In [8]:
# Muestra el tamaño del arreglo

A.size

9

<hr>

<h2 id="access">Acceder a los Elemento de un Arreglo Numpy</h2>

Podemos usar corchetes para acceder a los elementos del arreglo. La correspondencia entre los corchetes, la lista y la representación rectangular se muestra en la siguiente imagen para un arreglo de 3x3:

<img src="https://s3-api.us-geo.objectstorage.softlayer.net/cf-courses-data/CognitiveClass/PY0101EN/Chapter%205/Images/NumTwoEg.png" width="500" />

Podemos acceder a la segunda fila y tercera columna de la siguiente forma:

<img src="https://s3-api.us-geo.objectstorage.softlayer.net/cf-courses-data/CognitiveClass/PY0101EN/Chapter%205/Images/NumTwoFT.png" width="400" />

De forma simple usamos los corchetes y los índices que corresponde al elemento que queremos:

In [7]:
# Acceder al elemento de la segunda fila y tercera columna

A[1, 2]

23

La siguiente sintaxis también e puede usar para acceder a los elementos:

In [9]:
# Acceder al elemento de la segunda fila y tercera columna

A[1][2]

23

Considérese los elementos mostrados en la siguiente imagen:

<img src="https://s3-api.us-geo.objectstorage.softlayer.net/cf-courses-data/CognitiveClass/PY0101EN/Chapter%205/Images/NumTwoFF.png" width="400" />

Accedemos a los elementos de la siguiente manera:

In [10]:
# Acceder al elemento de la primera fila y primera columna

A[0][0]

11

Además, podemos aplicar slicing en los arreglos numpy. Observa la siguiente imagen. Nos gustaría obtener las primeras dos columnas y la primer fila.

<img src="https://s3-api.us-geo.objectstorage.softlayer.net/cf-courses-data/CognitiveClass/PY0101EN/Chapter%205/Images/NumTwoFSF.png" width="400" />

 Puede hacerse esto con la siguiente sintaxis

In [11]:
# Acceder a los elementos de la primera fila y la primera y segunda columna

A[0][0:2]

array([11, 12])

De igual manera, podemos obtener las primeras dos filas de la tercer columna de esta forma:

In [12]:
# Acceder a los elementos en la primera y segunda fila y tercer columna 

A[0:2, 2]

array([13, 23])

Esto corresponde a la siguiente imagen:

<img src="https://s3-api.us-geo.objectstorage.softlayer.net/cf-courses-data/CognitiveClass/PY0101EN/Chapter%205/Images/NumTwoTST.png" width="400" />

<hr>

<h2 id="op">Operaciones Básicas</h2>

También podemos hacer sumas entre arreglos. El proceso es idéntico al de la suma matricial. La suma matricial entre <code>X</code> y <code>Y</code> se muestra en la siguiente imagen:

<img src="https://s3-api.us-geo.objectstorage.softlayer.net/cf-courses-data/CognitiveClass/PY0101EN/Chapter%205/Images/NumTwoAdd.png" width="500" />

El arreglo Numpy esta dado por <code>X</code> y <code>Y</code>

In [14]:
# Crear un arreglo X tipo numpy

X = np.array([[1, 0], [0, 1]]) 
X

array([[1, 0],
       [0, 1]])

In [15]:
# Crear un arreglo Y tipo numpy

Y = np.array([[2, 1], [1, 2]]) 
Y

array([[2, 1],
       [1, 2]])

 Podemos sumar los arreglos de la siguiente manera.

In [16]:
# Sumar X y Y

Z = X + Y
Z

array([[3, 1],
       [1, 3]])

Multiplicar un arreglo por un escalar es idéntico a multiplicar una matriz por un escalar. Si multiplicamos la matriz <code>Y</code> por el escalar 2, simplemente se multiplica a cada elemento de la matriz por 2, como se muestra en la imagen:

<img src="https://s3-api.us-geo.objectstorage.softlayer.net/cf-courses-data/CognitiveClass/PY0101EN/Chapter%205/Images/NumTwoDb.png" width="500" />

Podemos realizar la misma operación en numpy de esta forma

In [18]:
# Crear un arreglo Y tipo numpy

Y = np.array([[2, 1], [1, 2]]) 
Y

array([[2, 1],
       [1, 2]])

In [19]:
# Multiplicar Y por 2

Z = 2 * Y
Z

array([[4, 2],
       [2, 4]])

La multiplicación de dos arreglos se corresponde al producto de Hadamard. Considérese las matrices <code>X</code> y <code>Y</code>. El producto de Hadamard es la multiplicación de cada elemento ubicado en la misma posición. En este caso, multiplicar los elementos que están en cajas del mismo color. El resultado es una nueva matriz de igual tamaño a <code>Y</code> o <code>X</code>, como se muestra a continuación:

<img src="https://s3-api.us-geo.objectstorage.softlayer.net/cf-courses-data/CognitiveClass/PY0101EN/Chapter%205/Images/NumTwoMul.png" width="500" />

Podemos realizar un producto de Hadamard del arreglo <code>X</code> y <code>Y</code> de la siguiente manera:

In [20]:
# Crear un arreglo Y tipo numpy

Y = np.array([[2, 1], [1, 2]]) 
Y

array([[2, 1],
       [1, 2]])

In [21]:
# Crear un arreglo X tipo numpy

X = np.array([[1, 0], [0, 1]]) 
X

array([[1, 0],
       [0, 1]])

In [22]:
# Multiplicar X por Y

Z = X * Y
Z

array([[2, 0],
       [0, 2]])

Podemos realizar una multiplicación matricial con los arreglos <code>A</code> y <code>B</code> de la siguiente forma:

Primero, definimos la matriz <code>A</code> y <code>B</code>:

In [23]:
# Creamos la matriz A

A = np.array([[0, 1, 1], [1, 0, 1]])
A

array([[0, 1, 1],
       [1, 0, 1]])

In [24]:
# Creamos la matriz B

B = np.array([[1, 1], [1, 1], [-1, 1]])
B

array([[ 1,  1],
       [ 1,  1],
       [-1,  1]])

Usamos la función <code>dot</code> para multiplicar los arreglos entre ellos.

In [25]:
# Calcular el producto matricial

Z = np.dot(A,B)
Z

array([[0, 2],
       [0, 2]])

In [26]:
# Calcular el seno de Z

np.sin(Z)

array([[0.        , 0.90929743],
       [0.        , 0.90929743]])

Utilizamos el atributo <code>T</code> para calcular la matriz transpuesta

In [30]:
# Creamos la matriz C

C = np.array([[1,1],[2,2],[3,3]])
C

array([[1, 1],
       [2, 2],
       [3, 3]])

In [31]:
# Obtener la transposición de C

C.T

array([[1, 2, 3],
       [1, 2, 3]])

<hr>
<h2>¡El último ejercicio!</h2>
<p>Felicidades, has completado tu primera lección y practica de laboratorio en Python. Sin embargo, hay algo mas que debes saber. La comunidad en Ciencia de Datos te alienta a compartir tu trabajo. La mejor forma de hacerlo es a través de GitHub. Al compartir tus cuadernos en GitHub, además de construir una reputación entre la comunidad de los científicos de datos, también te ayudará en el proceso de encontrar un trabajo. Incluso si este fuera tu primer material de trabajo, nunca es tarde para fomentar buenos hábitos. Por favor lee y analiza <a href="https://cognitiveclass.ai/blog/data-scientists-stand-out-by-sharing-your-notebooks/" target="_blank">este artículo</a> para aprender a compartir tu trabajo.
<hr>

<div class="alert alert-block alert-info" style="margin-top: 20px">
<h2>¡Obtén gratis IBM Watson Studio!</h2>
    <p><a href="https://cocl.us/PY0101EN_edx_add_bbottom"><img src="https://s3-api.us-geo.objectstorage.softlayer.net/cf-courses-data/CognitiveClass/PY0101EN/Ad/BottomAd.png" width="750" align="center"></a></p>
</div>

<h3>Acerca de los Autores:</h3>  
<p><a href="https://www.linkedin.com/in/joseph-s-50398b136/" target="_blank">Joseph Santarcangelo</a> es un Científico de Datos en IBM, además posee un doctorado en Ingeniería Eléctrica. Su trabajo de investigación se centra en el uso de Aprendizaje Automático (Machine Learning), Procesamiento de Señales y Visión Artificial para determinar el impacto de los videos en el proceso cognitivo. Joseph trabaja en IBM desde la terminación de su doctorado.</p>

Otros colaboradores: <a href="www.linkedin.com/in/jiahui-mavis-zhou-a4537814a">Mavis Zhou</a>

<hr>

<p>Copyright &copy; 2018 IBM Developer Skills Network. This notebook and its source code are released under the terms of the <a href="https://cognitiveclass.ai/mit-license/">MIT License</a>.</p>