<h3> Conozca un Arreglo numpy  </h3>

Utilizará el arreglo numpy <code> A</code> para lo siguiente  

In [1]:
import numpy as np
A=np.array([[11,12],[21,22],[31,32]])

1) escriba usando la función 'type' 

In [2]:
type(A)

numpy.ndarray

2) la forma del arreglo 

In [3]:
A.shape

(3, 2)

3) el tipo de datos en el arreglo 

In [5]:
A.dtype

dtype('int32')

4) Encuentre la segunda fila del arreglo numpy <code>A</code>:

In [6]:
A[2]

array([31, 32])

<h3> Dos tipos de Multiplicación    </h3>

utilizará los siguientes arreglos numpy para las siguientes preguntas 

In [7]:
A=np.array([[11,12],[21,22]])
B=np.array([[1, 0],[0,1]])

1) multiplique la matriz <code> A </code> y <code>B</code> 

In [8]:
A*B

array([[11,  0],
       [ 0, 22]])

2) trazar la función

In [10]:
np.dot(A,B) # producto matricial
np.dot(B,A)



array([[11, 12],
       [21, 22]])

<hr>
<small>Copyright &copy 2020 IBM Cognitive Class. Este cuaderno y su código fuente se publican bajo los términos de la [Licencia MIT] (https://cognitiveclass.ai/mit-license/).

</small>